### ISSUE TITLE
An unexpected error happened when opens App Configuration from Plugins > mSupply

### ISSUE THREAD

**Issue by Mai21** [openmsupply/msupply-dashboard-app#71]
In grafana v8.2, App Configuration is not shown.
![Screen Shot 2021-12-09 at 9 28 12 AM](https://user-images.githubusercontent.com/36495540/145279607-1b723896-0193-45b8-9d68-6fa5cba20754.png)

**Comment by sworup** [comment]
@Mai21 

The issue was, the language (internationalisation) file at `common/translations/en.json`, which was supposed to load before the plugin setting component was supposed to load, had not loaded completely before the plugin Content component attempts to load.

The code below was the culprit:

https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/frontend/src/containers/ConfigPageFactory.tsx#L28-L32

Now, normally the async `his.setState({ shouldLoad: true })` code should have waited for `intl.init` to trigger and completely load the file into a variable. But for some reason it wasn't.

Updating the code to-

```js
componentDidMount() {
      // TODO: More comprehensive localization solution
      intl.init({ currentLocale: 'en', locales }).then(() => {
        // After loading CLDR locale data, start to render
        this.setState({ shouldLoad: true });
      });
}
```

Seems to fix this issue.

I built the plugin (frontend only) with this change, signed and uploaded it to the `demo-board` server and the plugin configuration page is working now.

Building a PR.

**Comment by sworup** [comment]
@mark-prins PR is disabled in this repo for me. 😄

**Comment by sworup** [comment]
Maybe have to block loading component with a state variable here also:

https://github.com/openmsupply/msupply-dashboard-app/blob/3be59cd164d659ef04dddb78a80ce2b07d4fe07f/frontend/src/components/RootPage.tsx#L21-L23

**Comment by mark-prins** [comment]
> @mark-prins PR is disabled in this repo for me.

Hi Sworup - you're an admin on the repo.. not sure how you couldn't PR on it?

**Comment by sworup** [comment]
> Hi Sworup - you're an admin on the repo.. not sure how you couldn't PR on it?

@mark-prins I think Josh gave me admin rights a few minutes before you checked. 😆

**Comment by sworup** [comment]
@joshxg @mark-prins 
There is a new issue though, the configuration page loads but does not submit, it fails validation even if we fill all fields (I didn't change anything else then this PR's code).

I tried to tweak `ConfigurationForm` built it and uploaded it to the server in hopes of fixing it but no luck so I put it back the way it was (I promise I put it back). If am I am to fix this I might have to install the entire `mSupply-dashboard` repo too. Currently I was just trying to fix plugin in isolation.

**Comment by Mai21** [comment]
@sworup Thank you for fixing this!
